# https://github.com/mozilla/http-observatory.git
# https://github.com/mozilla/http-observatory/blob/master/httpobs/Dockerfile

FROM python:3.7-alpine

RUN apk --no-cache add \
    linux-headers \
    gcc \
    musl-dev \
    libpq-dev \
    git

RUN git clone https://github.com/mozilla/http-observatory

RUN apk del git

RUN install -d /var/run/httpobs /var/log/httpobs

WORKDIR /http-observatory

RUN pip install --upgrade --no-cache-dir \
    -r httpobs/requirements.txt \
    -r httpobs/database/requirements.txt \
    -r httpobs/scanner/requirements.txt \
    -r httpobs/website/requirements.txt

ENV PYTHONPATH $PYTHONPATH:/http-observatory

ENTRYPOINT $CONTAINERENTRYPOINT
