# https://github.com/erev0s/VAmPI.git
# https://github.com/erev0s/VAmPI/blob/master/Dockerfile (modified)

FROM python:3.7-alpine

RUN apk --update add \
    bash \
    nano \
    g++ \
    git

RUN git clone https://github.com/erev0s/VAmPI.git

ENV vulnerable=1
ENV tokentimetolive=60

WORKDIR /VAmPI

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["app.py"]
